spring:
    application:
        name: contacts
    boot:
      admin:
        client:
          url: http://localhost:8080
          instance:
            name: Contacts-Backend

data:
    mongodb:
        host: ${MONGO_HOST:localhost}
        port: ${MONGO_PORT:27017}
        database: ${MONGO_DB:contacts_db}
        auto-index-creation: true

aws:
  s3:
    bucket-name: ${S3_BUCKET:uxstudio-contacts}
    endpoint: ${S3_ENDPOINT:http://localhost:9000}
    region: ${S3_REGION:us-east-1}
    access-key: ${S3_ACCESS_KEY:minioadmin}
    secret-key: ${S3_SECRET_KEY:minioadmin}
    path-style-access: ${S3_PATH_STYLE:true}

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
